/**
 * constants.js
 *
 * Shared constants for Diverga v11.1 MCP infrastructure.
 * Single source of truth for checkpoint levels used by
 * sqlite-state.js, checkpoint-server.js, and others.
 *
 * v11.1 changes:
 *   - CP_VS_001, CP_VS_003: REQUIRED → RECOMMENDED (internal to owning agent)
 *   - CP_THEORY_SELECTION: REQUIRED → RECOMMENDED (own checkpoint of A2)
 *   - SCH_API_KEY_VALIDATION: REQUIRED → RECOMMENDED (own checkpoint of I1)
 */

export const CHECKPOINT_LEVELS = {
  // REQUIRED — gates downstream agents (5 total)
  CP_RESEARCH_DIRECTION: 'REQUIRED',
  CP_PARADIGM_SELECTION: 'REQUIRED',
  CP_METHODOLOGY_APPROVAL: 'REQUIRED',
  SCH_DATABASE_SELECTION: 'REQUIRED',
  SCH_SCREENING_CRITERIA: 'REQUIRED',

  // RECOMMENDED — important but not blocking
  CP_VS_001: 'RECOMMENDED',
  CP_VS_002: 'RECOMMENDED',
  CP_VS_003: 'RECOMMENDED',
  CP_THEORY_SELECTION: 'RECOMMENDED',
  SCH_API_KEY_VALIDATION: 'RECOMMENDED',
  CP_SCREENING_CRITERIA: 'RECOMMENDED',
  CP_QUALITY_REVIEW: 'RECOMMENDED',
  CP_INTEGRATION_STRATEGY: 'RECOMMENDED',
  CP_ANALYSIS_PLAN: 'RECOMMENDED',
  CP_SAMPLING_STRATEGY: 'RECOMMENDED',
  CP_CODING_APPROACH: 'RECOMMENDED',
  CP_THEME_VALIDATION: 'RECOMMENDED',
  CP_HUMANIZATION_REVIEW: 'RECOMMENDED',
  SCH_RAG_READINESS: 'RECOMMENDED',
  CP_JOURNAL_PRIORITIES: 'RECOMMENDED',
  CP_JOURNAL_SELECTION: 'RECOMMENDED',

  // OPTIONAL
  CP_VISUALIZATION_PREFERENCE: 'OPTIONAL',
  CP_SEARCH_STRATEGY: 'OPTIONAL',
  CP_HUMANIZATION_VERIFY: 'OPTIONAL',
};
